apiVersion: v1
kind: ConfigMap
metadata:
  name: slugbuilder-config
  labels:
    heritage: drycc
data:
  image: "quay.io/{{.Values.org}}/slugbuilder:{{.Values.docker_tag}}"
  pullpolicy: {{ .Values.pull_policy }}
