apiVersion: v1
kind: ConfigMap
metadata:
  name: slugbuilder-config
  labels:
    heritage: drycc
data:
  images.json: |
    [
        {
            "name": "heroku-18",
            "image": "{{.Values.image_registry}}/{{.Values.org}}/slugbuilder:{{.Values.image_tag}}.heroku-18"
        },
        {
            "name": "heroku-20",
            "image": "{{.Values.image_registry}}/{{.Values.org}}/slugbuilder:{{.Values.image_tag}}.heroku-20"
        }
    ]
  image_pull_policy: {{ .Values.image_pull_policy }}
