apiVersion: v1
kind: ConfigMap
metadata:
  name: slugbuilder-config
  labels:
    heritage: drycc
data:
  images.json: |
    [
        {
            "name": "heroku-18",
            "image": "{{.Values.docker_registry}}{{.Values.org}}/slugbuilder:{{.Values.docker_tag}}.heroku-18"
        },
        {
            "name": "heroku-20",
            "image": "{{.Values.docker_registry}}{{.Values.org}}/slugbuilder:{{.Values.docker_tag}}.heroku-20"
        }
    ]
  pull_policy: {{ .Values.pull_policy }}
