name: slugbuilder
home: https://github.com/drycc/slugbuilder
version: <Will be populated by the ci before publishing the chart>
description: Buildpack application builder for Drycc Workflow.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
