#!/usr/bin/env bash
set -eo pipefail

BUILDPACK_INSTALL_PATH="/tmp/buildpacks"

download_buildpack() {
    buildpack_url="$1"
    buildpack_commit="$2"
    buildpack_name="$3"

    echo "Fetching $buildpack_name..."

    set +e
    git clone --branch "$buildpack_commit" --depth 1 "$buildpack_url" $BUILDPACK_INSTALL_PATH/"$buildpack_name" &>/dev/null
    SHALLOW_CLONED=$?
    set -e
    if [ $SHALLOW_CLONED -ne 0 ]; then
        # if the shallow clone failed partway through, clean up and try a full clone
        rm -rf "${BUILDPACK_INSTALL_PATH:?}"/"$buildpack_name"
        git clone --quiet "$buildpack_url" $BUILDPACK_INSTALL_PATH/"$buildpack_name"
        pushd $BUILDPACK_INSTALL_PATH/"$buildpack_name" &>/dev/null
            git checkout --quiet "$buildpack_commit"
        popd &>/dev/null
    fi

    echo "Done."
}

mkdir -p $BUILDPACK_INSTALL_PATH

download_buildpack https://github.com/drycc/buildpack-clojure.git        main      clojure
download_buildpack https://github.com/drycc/buildpack-go.git             main      go
download_buildpack https://github.com/drycc/buildpack-gradle.git         main      gradle
download_buildpack https://github.com/drycc/buildpack-java.git           main      java
download_buildpack https://github.com/drycc/buildpack-nodejs.git         main      nodejs
download_buildpack https://github.com/drycc/buildpack-php.git            main      php   
download_buildpack https://github.com/drycc/buildpack-python.git         main      python
download_buildpack https://github.com/drycc/buildpack-ruby.git           main      ruby
download_buildpack https://github.com/drycc/buildpack-scala.git          main      scala

chown -R slug:slug $BUILDPACK_INSTALL_PATH
