#!/usr/bin/env bash
set -eo pipefail

BUILDPACK_INSTALL_PATH="/tmp/buildpacks"

download_buildpack() {
    buildpack_url="$1"
    buildpack_commit="$2"
    buildpack_name="$3"

    echo "Fetching $buildpack_name..."

    set +e
    git clone --branch "$buildpack_commit" --depth 1 "$buildpack_url" $BUILDPACK_INSTALL_PATH/"$buildpack_name" &>/dev/null
    SHALLOW_CLONED=$?
    set -e
    if [ $SHALLOW_CLONED -ne 0 ]; then
        # if the shallow clone failed partway through, clean up and try a full clone
        rm -rf "${BUILDPACK_INSTALL_PATH:?}"/"$buildpack_name"
        git clone --quiet "$buildpack_url" $BUILDPACK_INSTALL_PATH/"$buildpack_name"
        pushd $BUILDPACK_INSTALL_PATH/"$buildpack_name" &>/dev/null
            git checkout --quiet "$buildpack_commit"
        popd &>/dev/null
    fi

    echo "Done."
}

mkdir -p $BUILDPACK_INSTALL_PATH

download_buildpack https://github.com/heroku/heroku-buildpack-clojure.git        v85      clojure
download_buildpack https://github.com/heroku/heroku-buildpack-go.git             v144     go
download_buildpack https://github.com/heroku/heroku-buildpack-gradle.git         v31      gradle
download_buildpack https://github.com/heroku/heroku-buildpack-java.git           v66      java
download_buildpack https://github.com/heroku/heroku-buildpack-nodejs.git         v174     nodejs
download_buildpack https://github.com/heroku/heroku-buildpack-php.git            v178     php   
download_buildpack https://github.com/heroku/heroku-buildpack-python.git         v174     python
download_buildpack https://github.com/heroku/heroku-buildpack-ruby.git           v218     ruby
download_buildpack https://github.com/heroku/heroku-buildpack-scala.git          v87      scala

chown -R slug:slug $BUILDPACK_INSTALL_PATH
