#!/usr/bin/env bash
set -eo pipefail

apt-get update
apt-get install -y hashdeep

chown -R slug:slug /app
chown slug:slug /usr/local/bin/get_object \
                /usr/local/bin/normalize_storage \
                /usr/local/bin/put_object \
                /usr/local/bin/read_procfile_keys \
                /usr/local/bin/restore_cache \
                /usr/local/bin/store_cache
