FROM heroku/heroku:18-build

ENV STACK heroku-18
ENV CNB_STACK_ID heroku-18
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONPATH $PYTHONPATH:/usr/local/lib/python3/site-packages

ADD . /

RUN /installer/install

USER slug
ENV HOME /app

ENTRYPOINT ["/builder/build.sh"]
