FROM heroku/heroku:18-build

ENV STACK heroku-18
ENV CNB_STACK_ID heroku-18
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONPATH $PYTHONPATH:/usr/local/lib/python3/site-packages

ADD . /

RUN /builder/install-tools \
  && /builder/cleanup

USER slug
ENV HOME /app
RUN /builder/install-buildpacks

ENTRYPOINT ["/builder/build.sh"]
