FROM heroku/heroku:20-build

ENV STACK heroku-20
ENV CNB_STACK_ID heroku-20
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONPATH $PYTHONPATH:/usr/local/lib/python3/site-packages

ADD . /

RUN /builder/install-tools \
  && /builder/cleanup

USER slug
ENV HOME /app
RUN /builder/install-buildpacks

ENTRYPOINT ["/builder/build.sh"]
